services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    env_file: .env
    # ports:
    #   - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/data:ro
    env_file: .env
    ports:
      - "10002:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_network

volumes:
  postgres_data:
  data:

networks:
  backend_network:
    driver: bridge